language: ruby
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.5
  - 2.6.5
  - 2.7.0
dist: xenial
before_install:
  - scripts/build-libsodium
script:
  - bundle exec rspec
  - bundle exec rubocop
cache: bundler
env:
  - CODECOV=true
