name: CI

on:
  pull_request:

  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    name: build ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.7', '3.0', '3.1', truffleruby-head ]

    steps:
      - uses: actions/checkout@v2
      - name: Install libsodium
        run: scripts/build-libsodium
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Test
        run: bundle exec rspec
      - name: Linting
        run: bundle exec rubocop
